function plot_additional_bins(app)
    % Create a dialog window
    d = dialog('Position', [500 400 300 180], ...
        'Name', 'Enter Bin Numbers to Add (MATLAB Syntax)', ...
        'Color', [0.95 0.95 0.95], ...
        'WindowStyle', 'modal');

    % Instruction label
    uicontrol('Parent', d, ...
    'Style', 'text', ...
    'Position', [30 120 240 30], ...
    'String', 'Enter Bin Numbers to Add:', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.95 0.95 0.95], ...
    'HorizontalAlignment', 'center');

    % Bin number label
    uicontrol('Parent', d, ...
    'Style', 'text', ...
    'Position', [20 80 80 20], ...
    'String', 'Bin number:', ...
    'FontSize', 10, ...
    'BackgroundColor', [0.95 0.95 0.95], ...
    'HorizontalAlignment', 'right');

    % Bin number input field
    binField = uicontrol('Parent', d, ...
                'Style', 'edit', ...
                'Position', [110 80 150 25], ...
                'FontSize', 10, ...
                'BackgroundColor', 'white');

    % OK button
    uicontrol('Parent', d, ...
    'Position', [115 30 70 30], ...
    'String', 'OK', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.6 0.8 1], ...
    'Callback', @(src, event) onConfirm());

    % Wait for the dialog to close before returning
    uiwait(d);

    % Callback for OK button
    function onConfirm()
        % erp_num = str2double(erpField.String);
        bin_nums = eval(binField.String);

        % Remove the current bin from this
        bin_nums(bin_nums == app.bin_num) = [];

        % Plot the additional bins
        if ~isempty(bin_nums)
            hold(app.erp_display, 'on')
            
            current_erp = app.erp_num;
            electrodes = app.cfg.electrodes;

            % plot all other bins with color
            for additional_bin = bin_nums
                plot( ...
                    app.time_vector, ...
                    squeeze(app.erp_mat(current_erp, electrodes, :, additional_bin)), '--', ...
                    'Color', [0.7, 0.7, 1], ...
                    'Parent', app.erp_display, ...
                    'DisplayName', strcat('Bin ', num2str(additional_bin)))
            end

            % Add the legend

            hold(app.erp_display, 'off')
        end

        uiresume(d);  % Resume execution of the main function
        delete(d);    % Close the dialog
    end
end
